name: CI/CD Pipeline

on:
  push:
    branches:  [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
             python -m pip install --upgrade pip
             pip install -r requirements.txt
             pip install flake8

      - name: Run tests
        run: echo "No tests yet, pipeline continues..."
        
      - name: Run Linter
        run: flake8 .
        
      - name: Run tests
        run: pytest -v

      - name: Build Docker image
        run: docker build -t flask-cicd-demo .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        run: |
          docker tag flask-cicd-demo ${{ secrets.DOCKER_USERNAME }}/flask-cicd-demo:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flask-cicd-demo:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          hosts: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ secrets.DOCKER_USERNAME }}/flask-cicd-demo:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d -p 5000:5000 --name flask-app ${{ secrets.DOCKER_USERNAME }}/flask-cicd-demo:latest
